# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name cov_expo_iso_cpp
#'
#' @title Isotropic exponential covariance function (C++ version)
#'
#' @param x1 First location (vector)
#' @param x2 Second location (vector)
#' @param covparms A numerical vector with covariance parameters in the form (variance, range)
#'
#' @return The isotropic exponenital covariance between the locations provided
cov_expo_iso_cpp <- function(x1, x2, covparms) {
    .Call(`_correlationVecchia_cov_expo_iso_cpp`, x1, x2, covparms)
}

#' @name cov_expo_aniso_cpp
#'
#' @title Anisotropic exponential covariance function (C++ version)
#'
#' @param x1 First location (vector)
#' @param x2 Second location (vector)
#' @param covparms A numerical vector with covariance parameters in the form (variance, range, anisotropy for the first dimension)
#'
#' @return The anisotropic exponenital covariance between the locations provided
cov_expo_aniso_cpp <- function(x1, x2, covparms) {
    .Call(`_correlationVecchia_cov_expo_aniso_cpp`, x1, x2, covparms)
}

#' @name cov_expo_spacetime_cpp
#'
#' @title Space-time exponential covariance function (C++ version)
#'
#' @param x1 First location (vector)
#' @param x2 Second location (vector)
#' @param covparms A numerical vector with covariance parameters in the form (variance, spatial range, temporal range)
#'
#' @return The space-time exponenital covariance between the locations provided
cov_expo_spacetime_cpp <- function(x1, x2, covparms) {
    .Call(`_correlationVecchia_cov_expo_spacetime_cpp`, x1, x2, covparms)
}

#' @name cov_expo_squared_cpp
#'
#' @title Squared exponential covariance function (C++ version)
#'
#' @param x1 First location (vector)
#' @param x2 Second location (vector)
#' @param covparms A numerical vector with covariance parameters in the form (variance, range)
#'
#' @return The squared exponenital covariance between the locations provided
cov_expo_squared_cpp <- function(x1, x2, covparms) {
    .Call(`_correlationVecchia_cov_expo_squared_cpp`, x1, x2, covparms)
}

#' @name cov_matern_iso_cpp
#'
#' @title Isotropic Matern covariance function (C++ version)
#'
#' @param x1 First location (vector)
#' @param x2 Second location (vector)
#' @param covparms A numerical vector with covariance parameters in the form (sigma2, range, smoothness)
#'
#' @return The isotropic Matern covariance between the locations provided
cov_matern_iso_cpp <- function(x1, x2, covparms) {
    .Call(`_correlationVecchia_cov_matern_iso_cpp`, x1, x2, covparms)
}

#' @name cov_matern_aniso_cpp
#'
#' @title Anisotropic Matern covariance function (C++ version)
#'
#' @param x1 First location (vector)
#' @param x2 Second location (vector)
#' @param covparms A numerical vector with covariance parameters in the form (sigma2, range, smoothness, anisotropy for the first dimension)
#'
#' @return The Anisotropic Matern covariance between the locations provided
cov_matern_aniso_cpp <- function(x1, x2, covparms) {
    .Call(`_correlationVecchia_cov_matern_aniso_cpp`, x1, x2, covparms)
}

#' @name cov_matern_scaledim_cpp
#'
#' @title Anisotropic Matern covariance function (C++ version)
#'
#' @param x1 First location (vector)
#' @param x2 Second location (vector)
#' @param covparms A numerical vector with covariance parameters = (sigma2, range_1, ... , range_d, smoothness)
#'
#' @return The Anisotropic Matern covariance between the locations provided
cov_matern_scaledim_cpp <- function(x1, x2, covparms) {
    .Call(`_correlationVecchia_cov_matern_scaledim_cpp`, x1, x2, covparms)
}

#' @name cov_matern_spacetime_cpp
#'
#' @title Space-time Matern covariance function (C++ version)
#'
#' @param x1 First location (vector)
#' @param x2 Second location (vector)
#' @param covparms A numerical vector with covariance parameters = (sigma2, spatial range, temporal range, smoothness)
#'
#' @return The space-time Matern covariance between the locations provided
cov_matern_spacetime_cpp <- function(x1, x2, covparms) {
    .Call(`_correlationVecchia_cov_matern_spacetime_cpp`, x1, x2, covparms)
}

#' @name cov_matern_ns_forR
#'
#' @title Nonstationary Matern covariance function (similar to R version, but slower than R version)
#'
#' @param locs1 A numerical matrix with \code{n} rows and \code{p} columns. Each row of locs1 gives a point of the first set in R^d
#' @param locs2 A numerical matrix with \code{n} rows and \code{p} columns. Each row of locs2 gives a point of the second set in R^d
#' @param sigma A numeric function for spatially varying standard deviation \eqn{\sigma( loc )}
#' @param smoothness A numeric function for spatially varying smoothness \eqn{\nu( loc )}
#' @param kernel A matrix-valued function for spatially varying (local) geometric anisotropy \eqn{\Sigma( loc )}
#'
#' @return The nonstationary Matern covariance between the locations provided
cov_matern_ns_forR <- function(locs1, locs2, sigma, smoothness, kernel) {
    .Call(`_correlationVecchia_cov_matern_ns_forR`, locs1, locs2, sigma, smoothness, kernel)
}

#' @name cal_matern_ns
#'
#' @title For fast calculation of nonstationary Matern covariance (See cov_matern_ns)
#'
#' @param locs A numeric matrix of locations
#' @param sigvec A vector of variance parameters
#' @param nuvec A vector of smoothness parameters
#' @param kerList A list of kernel matrices
#'
#' @return The nonstationary Matern covariance matrix of the locations provided
cal_matern_ns <- function(locs, sigvec, nuvec, kerList) {
    .Call(`_correlationVecchia_cal_matern_ns`, locs, sigvec, nuvec, kerList)
}

#' @name cov_matern_ns_cpp
#'
#' @title Nonstationary Matern covariance function (C++ version)
#'
#' @param x1 First location (vector)
#' @param x2 Second location (vector)
#' @param sigma A numeric function for spatially varying standard deviation \eqn{\sigma( loc )}
#' @param smoothness A numeric function for spatially varying smoothness \eqn{\nu( loc )}
#' @param kernel A matrix-valued function for spatially varying (local) geometric anisotropy \eqn{\Sigma( loc )}
#'
#' @return The nonstationary Matern covariance between the locations provided
cov_matern_ns_cpp <- function(x1, x2, sigma, smoothness, kernel) {
    .Call(`_correlationVecchia_cov_matern_ns_cpp`, x1, x2, sigma, smoothness, kernel)
}

#' @name cov_latentDim_biv_cpp
#'
#' @title Isotropic exponential covariance function for bivariate Gaussian Processes using latent dimensions (C++ version)
#'
#' @param x1 First location (vector)
#' @param x2 Second location (vector)
#' @param covparms A numerical vector with covariance parameters = (sigma2, range, latent dimension, x1's id, x2's id). ID can be either 1 or 2.
#'
#' @return The isotropic exponential covariance between the locations provided with respect to latent dimension and their ids
cov_latentDim_biv_cpp <- function(x1, x2, covparms) {
    .Call(`_correlationVecchia_cov_latentDim_biv_cpp`, x1, x2, covparms)
}

#' @name cov_latentDim_triv_cpp
#'
#' @title Isotropic exponential covariance function for trivariate Gaussian Processes using latent dimensions (C++ version)
#'
#' @param x1 First location (vector)
#' @param x2 Second location (vector)
#' @param covparms A numerical vector with covariance parameters = (sigma2, range, latent dimension, x1's id, x2's id). ID can be 1 or 2, or 3.
#'
#' @return The isotropic exponential covariance between the locations provided with respect to latent dimension and their ids
cov_latentDim_triv_cpp <- function(x1, x2, covparms) {
    .Call(`_correlationVecchia_cov_latentDim_triv_cpp`, x1, x2, covparms)
}

#' @name GpGp_matern_spacetime
#'
#' @title GpGp package's matern_spacetime function (C++ version) (CAUTION: different from cov_matern_spacetime)
#'
#' @param x1 First location (vector)
#' @param x2 Second location (vector)
#' @param covparms A numerical vector with covariance parameters = (sigma2, spatial range, temporal range, smoothness, nugget)
#'
#' @return The space-time Matern covariance between the locations provided (CAUTION: different from cov_matern_spacetime)
GpGp_matern_spacetime_cpp <- function(x1, x2, covparms) {
    .Call(`_correlationVecchia_GpGp_matern_spacetime_cpp`, x1, x2, covparms)
}

#' @name fun_Rcpp_example
#'
#' @title Example function
#'
#' @param a First argument: real number
#' @param x Second argument: A vector
#'
#' @return Product of a and x
fun_Rcpp_example <- function(a, x) {
    .Call(`_correlationVecchia_fun_Rcpp_example`, a, x)
}

#' @name mat2vals
#'
#' @title mat2vals
#'
#' @param ptrs Pointers for sparse matrix
#' @param inds Indices for sparse matrix
#' @param covmat A covariance matrix
#'
#' @return A vector of covariance values
mat2vals <- function(ptrs, inds, covmat) {
    .Call(`_correlationVecchia_mat2vals`, ptrs, inds, covmat)
}

#' @name sortSparse_Rcpp
#'
#' @title Florian's Algorithm without unmeasured inputs (C++ version)
#'
#' @param x A numerical matrix of inputs (locations)
#' @param rho hyperparameter rho (instead of m)
#' @param initInd initial input number
#' @param distype euclidean or correlation
#' @param fstr covariance function name
#' @param covparms A numerical vector with covariance parameters
#'
#' @return List. Check it out!
sortSparse_Rcpp <- function(x, rho, initInd, distype, fstr, covparms) {
    .Call(`_correlationVecchia_sortSparse_Rcpp`, x, rho, initInd, distype, fstr, covparms)
}

#' @name predSortSparse_Rcpp
#'
#' @title Florian's Algorithm with unmeasured inputs (C++ version)
#'
#' @param xTrain A numerical matrix of inputs (measured)
#' @param xTest A numerical matrix of inputs (not measured)
#' @param rho hyperparameter rho (instead of m)
#' @param initInd initial input number
#' @param distype euclidean or correlation
#' @param fstr covariance function name
#' @param covparms A numerical vector with covariance parameters
#'
#' @return List. Check it out!
predSortSparse_Rcpp <- function(xTrain, xTest, rho, initInd, distype, fstr, covparms) {
    .Call(`_correlationVecchia_predSortSparse_Rcpp`, xTrain, xTest, rho, initInd, distype, fstr, covparms)
}

#' @name NNcheck_Rcpp
#'
#' @title NNcheck_Rcpp (only for Florian's algorithm)
#'
#' @param I I
#' @param J J
#' @param P P
#' @param distances distances
#' @param x x
#' @param rho rho
#' @param distype distype
#' @param fstr fstr
#' @param covparms covparms
#'
#' @return Matrix. Check it out!
NNcheck_Rcpp <- function(I, J, P, distances, x, rho, distype, fstr, covparms) {
    .Call(`_correlationVecchia_NNcheck_Rcpp`, I, J, P, distances, x, rho, distype, fstr, covparms)
}

#' @name NNcheck_both_Rcpp
#'
#' @title creating both smaller and larger sparsity patterns (only for Florian's algorithm)
#'
#' @param I I
#' @param J J
#' @param P P
#' @param distances distances
#' @param x x
#' @param rho rho
#' @param distype distype
#' @param fstr fstr
#' @param covparms covparms
#'
#' @return list of rowvecs
NNcheck_both_Rcpp <- function(I, J, P, distances, x, rho, distype, fstr, covparms) {
    .Call(`_correlationVecchia_NNcheck_both_Rcpp`, I, J, P, distances, x, rho, distype, fstr, covparms)
}

#' @name conditioning_rho_Rcpp
#'
#' @title conditioning based on Florian's algorithm (C++ version)
#'
#' @param indvec indvec
#' @param condvec condvec
#' @param P P
#' @param maxsize maxsize
#' @param x x
#' @param distype euclidean or correlation
#' @param fstr covariance function name
#' @param covparms A numerical vector with covariance parameters
#'
#' @return Matrix. Check it out!
conditioning_rho_Rcpp <- function(indvec, condvec, P, maxsize, x, distype, fstr, covparms) {
    .Call(`_correlationVecchia_conditioning_rho_Rcpp`, indvec, condvec, P, maxsize, x, distype, fstr, covparms)
}

#' @name conditioning_m_Rcpp
#'
#' @title Nearest-Neighbor (NN) conditioning with respect to user-specified distance matrix
#'
#' @param m Number of nearby points to condition on
#' @param d A matrix of distances between locations (for instance, 1 - cor)
#'
#' @return A matrix of indices giving NN conditioning sets
conditioning_m_Rcpp <- function(m, d) {
    .Call(`_correlationVecchia_conditioning_m_Rcpp`, m, d)
}

