# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cov_cpp <- function(x1, x2, covparms) {
    .Call(`_correlationVecchia_cov_cpp`, x1, x2, covparms)
}

cov_expo_iso_cpp <- function(x1, x2, covparms) {
    .Call(`_correlationVecchia_cov_expo_iso_cpp`, x1, x2, covparms)
}

cov_expo_aniso_cpp <- function(x1, x2, covparms) {
    .Call(`_correlationVecchia_cov_expo_aniso_cpp`, x1, x2, covparms)
}

cov_matern_iso_cpp <- function(x1, x2, covparms) {
    .Call(`_correlationVecchia_cov_matern_iso_cpp`, x1, x2, covparms)
}

cov_matern_aniso_cpp <- function(x1, x2, covparms) {
    .Call(`_correlationVecchia_cov_matern_aniso_cpp`, x1, x2, covparms)
}

cov_matern_spacetime_cpp <- function(x1, x2, covparms) {
    .Call(`_correlationVecchia_cov_matern_spacetime_cpp`, x1, x2, covparms)
}

cov_matern_2p5_cpp <- function(x1, x2, covparms) {
    .Call(`_correlationVecchia_cov_matern_2p5_cpp`, x1, x2, covparms)
}

sortSparse_Rcpp <- function(x, rho, initInd, distype, fstr, covparms) {
    .Call(`_correlationVecchia_sortSparse_Rcpp`, x, rho, initInd, distype, fstr, covparms)
}

predSortSparse_Rcpp <- function(xTrain, xTest, rho, initInd, distype, fstr, covparms) {
    .Call(`_correlationVecchia_predSortSparse_Rcpp`, xTrain, xTest, rho, initInd, distype, fstr, covparms)
}

NNcheck_Rcpp <- function(I, J, P, distances, x, rho, distype, fstr, covparms) {
    .Call(`_correlationVecchia_NNcheck_Rcpp`, I, J, P, distances, x, rho, distype, fstr, covparms)
}

conditioning_Rcpp <- function(indvec, condvec, P, maxsize, x, distype, fstr, covparms) {
    .Call(`_correlationVecchia_conditioning_Rcpp`, indvec, condvec, P, maxsize, x, distype, fstr, covparms)
}

index_smallest <- function(target) {
    .Call(`_correlationVecchia_index_smallest`, target)
}

index_smallestk <- function(target, k) {
    .Call(`_correlationVecchia_index_smallestk`, target, k)
}

conditioning_nn_Rcpp <- function(m, d) {
    .Call(`_correlationVecchia_conditioning_nn_Rcpp`, m, d)
}

