# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cov_cpp <- function(x1, x2, covparms) {
    .Call(`_correlationVecchia_cov_cpp`, x1, x2, covparms)
}

cov_expo_iso_cpp <- function(x1, x2, covparms) {
    .Call(`_correlationVecchia_cov_expo_iso_cpp`, x1, x2, covparms)
}

cov_expo_aniso_cpp <- function(x1, x2, covparms) {
    .Call(`_correlationVecchia_cov_expo_aniso_cpp`, x1, x2, covparms)
}

sortSparse_Rcpp <- function(x, rho, initInd, distype, fstr, covparms) {
    .Call(`_correlationVecchia_sortSparse_Rcpp`, x, rho, initInd, distype, fstr, covparms)
}

NNcheck_Rcpp <- function(I, J, P, distances, x, rho, distype, fstr, covparms) {
    .Call(`_correlationVecchia_NNcheck_Rcpp`, I, J, P, distances, x, rho, distype, fstr, covparms)
}

conditioning_Rcpp <- function(indvec, condvec, P, maxsize, x, distype, fstr, covparms) {
    .Call(`_correlationVecchia_conditioning_Rcpp`, indvec, condvec, P, maxsize, x, distype, fstr, covparms)
}

